import { IQuest, list_bag, list_item } from "./types"

export const QUESTS_LIST_COMMON: IQuest[] = [
  {
    title: "3 level 2 items",
    required_item: 3,
    required_type: "A2",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_bag[0],
  },
  {
    title: "1 level 5 items",
    required_item: 1,
    required_type: "A5",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[7],
  },
  {
    title: "1 level 2 items",
    required_item: 1,
    required_type: "A2",
    current_progress: 0,
    reward_type: "point",
    reward_point: 100,
  },
  {
    title: "2 level 3 items",
    required_item: 2,
    required_type: "A3",
    current_progress: 0,
    reward_type: "point",
    reward_point: 150,
  },
  {
    title: "1 level 4 items",
    required_item: 1,
    required_type: "A4",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[6],
  },
  {
    title: "1 level 3 items",
    required_item: 1,
    required_type: "A3",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[4],
  },
  {
    title: "1 level 1 items",
    required_item: 1,
    required_type: "A1",
    current_progress: 0,
    reward_type: "point",
    reward_point: 50,
  },
  {
    title: "2 level 1 items",
    required_item: 2,
    required_type: "A1",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[1],
  },
  {
    title: "2 level 4 items",
    required_item: 2,
    required_type: "A4",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[5],
  },
  {
    title: "3 level 1 items",
    required_item: 3,
    required_type: "A1",
    current_progress: 0,
    reward_type: "point",
    reward_point: 75,
  },
  {
    title: "2 level 5 items",
    required_item: 2,
    required_type: "A5",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[8],
  },
  {
    title: "1 level 6 items",
    required_item: 1,
    required_type: "A6",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[9],
  },
  {
    title: "2 level 2 items",
    required_item: 2,
    required_type: "A2",
    current_progress: 0,
    reward_type: "point",
    reward_point: 125,
  },
  {
    title: "1 level 7 items",
    required_item: 1,
    required_type: "A7",
    current_progress: 0,
    reward_type: "item",
    reward_item: list_item[10],
  },
]
